server:
  port: 8080
  servlet.context-path: /

  # 开启 HTTPS 支持，首先应创建 keystore: keytool -keystore mykeys.jks -genkey -alias tomcat -keyalg RSA
#  ssl:
#    key-store: classpath:mykeys.jks
#    key-store-password: spring
#    key-password: spring


# 日志
logging:
  level:
    root: INFO
    com.hitech.wechat.api.demo: DEBUG


# 数据源配置，无需显示指定 driver-class-name 会根据 url 识别出需要什么驱动。
spring:
  datasource:
    url: jdbc:mysql://39.106.228.124:3306/hitech?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: hitech
    password: 20190422

  # thymeleaf 模板配置
#  thymeleaf.prefix: classpath:/templates/
#  thymeleaf.suffix: .html
#  thymeleaf.mode: HTML
#  thymeleaf.encoding: UTF-8
#  thymeleaf.cache: false

  resources.chain.strategy.content.enabled: true
  resources.chain.strategy.content.paths: /**

  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: Asia/Shanghai
  jackson.default-property-inclusion: non_null
